theme: jekyll-theme-cayman

plugins:
  - jekyll-redirect-from

title:
  Tasks for Wrike
description:
  TODOリストライクなWrikeクライアントアプリ

tryinguse_btn:
  show_button: false
  btn_url: https://tasks.kaniyama.net/